ifeq ($(strip $(TARGET_BOOTLOADER_BOARD_NAME)),encore)

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := watchdogd
LOCAL_MODULE_PATH := $(TARGET_ROOT_OUT_SBIN)
LOCAL_MODULE_TAGS := optional

LOCAL_SRC_FILES := watchdogd.c

LOCAL_PRELINK_MODULE := false
LOCAL_STATIC_LIBRARIES := libc
LOCAL_FORCE_STATIC_EXECUTABLE := true
include $(BUILD_EXECUTABLE)

endif
